[package]
name = "ez-jsonrpc"
version = "0.4.0"

description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ez-jsonrpc-types = { path = "types", version = "0.5.1" }
ez-jsonrpc-macros = { path = "macros", version = "0.1.1" }
ryu = "1.0.18"
serde = "1.0.205"
serde_json = "1.0.122"
tower-layer = "0.3.3"
tower-service = "0.3.3"
futures-util = { version = "0.3.31", default-features = false, features = [
    "async-await",
    "async-await-macro",
    "sink",
    "std",
] }
pin-project-lite = "0.2.15"
futures-channel = { version = "0.3.31", features = ["alloc"] }
either = { version = "1.13.0", default-features = false }
fsmentry = { version = "0.2.0", default-features = false, features = ["macros"] }

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/ez-jsonrpc"
repository = "https://github.com/aatifsyed/ez-jsonrpc"
homepage = "https://crates.io/crates/ez-jsonrpc"
description = "JSON-RPC 2.0 made easy!"

[dev-dependencies]
anyhow = "1.0.91"
bytes = "1.8.0"
futures = "0.3.31"
serde_json = { version = "1.0.132", features = ["raw_value"] }
tap = "1.0.1"
tokio = { version = "1.41.0", features = ["full"] }
tokio-tungstenite = "0.24.0"
tokio-util = { version = "0.7.12", features = ["full"] }
tower = { version = "0.5.1", features = ["util"] }

[workspace]
members = ["_doctest", "macros", "types"]
